# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nfs/slac/g/beamphysics/gzhou/cmake/bin/cmake

# The command to remove a file.
RM = /nfs/slac/g/beamphysics/gzhou/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /nfs/slac/g/beamphysics/gzhou/Yuri

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /nfs/slac/g/beamphysics/gzhou/Yuri

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nfs/slac/g/beamphysics/gzhou/cmake/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/nfs/slac/g/beamphysics/gzhou/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/slac/g/beamphysics/gzhou/Yuri/CMakeFiles /nfs/slac/g/beamphysics/gzhou/Yuri/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/slac/g/beamphysics/gzhou/Yuri/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yuri

# Build rule for target.
yuri: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yuri
.PHONY : yuri

# fast build rule for target.
yuri/fast:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/build
.PHONY : yuri/fast

Readin.o: Readin.cpp.o

.PHONY : Readin.o

# target to build an object file
Readin.cpp.o:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/Readin.cpp.o
.PHONY : Readin.cpp.o

Readin.i: Readin.cpp.i

.PHONY : Readin.i

# target to preprocess a source file
Readin.cpp.i:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/Readin.cpp.i
.PHONY : Readin.cpp.i

Readin.s: Readin.cpp.s

.PHONY : Readin.s

# target to generate assembly for a file
Readin.cpp.s:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/Readin.cpp.s
.PHONY : Readin.cpp.s

Sdomain.o: Sdomain.cpp.o

.PHONY : Sdomain.o

# target to build an object file
Sdomain.cpp.o:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/Sdomain.cpp.o
.PHONY : Sdomain.cpp.o

Sdomain.i: Sdomain.cpp.i

.PHONY : Sdomain.i

# target to preprocess a source file
Sdomain.cpp.i:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/Sdomain.cpp.i
.PHONY : Sdomain.cpp.i

Sdomain.s: Sdomain.cpp.s

.PHONY : Sdomain.s

# target to generate assembly for a file
Sdomain.cpp.s:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/Sdomain.cpp.s
.PHONY : Sdomain.cpp.s

Writeout.o: Writeout.cpp.o

.PHONY : Writeout.o

# target to build an object file
Writeout.cpp.o:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/Writeout.cpp.o
.PHONY : Writeout.cpp.o

Writeout.i: Writeout.cpp.i

.PHONY : Writeout.i

# target to preprocess a source file
Writeout.cpp.i:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/Writeout.cpp.i
.PHONY : Writeout.cpp.i

Writeout.s: Writeout.cpp.s

.PHONY : Writeout.s

# target to generate assembly for a file
Writeout.cpp.s:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/Writeout.cpp.s
.PHONY : Writeout.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/yuri.dir/build.make CMakeFiles/yuri.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... yuri"
	@echo "... Readin.o"
	@echo "... Readin.i"
	@echo "... Readin.s"
	@echo "... Sdomain.o"
	@echo "... Sdomain.i"
	@echo "... Sdomain.s"
	@echo "... Writeout.o"
	@echo "... Writeout.i"
	@echo "... Writeout.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

